/*
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TransactionDirection
 */
@JsonAdapter(TransactionDirection.Adapter.class)
public enum TransactionDirection {
  
  TransactionDirectionOut("OUT"),
  
  TransactionDirectionIn("IN");

  private String value;

  TransactionDirection(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransactionDirection fromValue(String value) {
    for (TransactionDirection b : TransactionDirection.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TransactionDirection> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransactionDirection enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TransactionDirection read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TransactionDirection.fromValue(value);
    }
  }
}

