/*
 * Wallet API Documentation
 * This is a custody wallet service api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CurrencyNetwork
 */
public class CurrencyNetworkTest {
    private final CurrencyNetwork model = new CurrencyNetwork();

    /**
     * Model tests for CurrencyNetwork
     */
    @Test
    public void testCurrencyNetwork() {
        // TODO: test CurrencyNetwork
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'canDeposit'
     */
    @Test
    public void canDepositTest() {
        // TODO: test canDeposit
    }

    /**
     * Test the property 'canTransfer'
     */
    @Test
    public void canTransferTest() {
        // TODO: test canTransfer
    }

    /**
     * Test the property 'canWithdraw'
     */
    @Test
    public void canWithdrawTest() {
        // TODO: test canWithdraw
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'feeCurrency'
     */
    @Test
    public void feeCurrencyTest() {
        // TODO: test feeCurrency
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'maxFee'
     */
    @Test
    public void maxFeeTest() {
        // TODO: test maxFee
    }

    /**
     * Test the property 'maxFeeForCtAddr'
     */
    @Test
    public void maxFeeForCtAddrTest() {
        // TODO: test maxFeeForCtAddr
    }

    /**
     * Test the property 'maxWithdrawAmount'
     */
    @Test
    public void maxWithdrawAmountTest() {
        // TODO: test maxWithdrawAmount
    }

    /**
     * Test the property 'minCollectAmount'
     */
    @Test
    public void minCollectAmountTest() {
        // TODO: test minCollectAmount
    }

    /**
     * Test the property 'minConfirmations'
     */
    @Test
    public void minConfirmationsTest() {
        // TODO: test minConfirmations
    }

    /**
     * Test the property 'minDepositAmount'
     */
    @Test
    public void minDepositAmountTest() {
        // TODO: test minDepositAmount
    }

    /**
     * Test the property 'minFee'
     */
    @Test
    public void minFeeTest() {
        // TODO: test minFee
    }

    /**
     * Test the property 'minFeeForCtAddr'
     */
    @Test
    public void minFeeForCtAddrTest() {
        // TODO: test minFeeForCtAddr
    }

    /**
     * Test the property 'minWithdrawAmount'
     */
    @Test
    public void minWithdrawAmountTest() {
        // TODO: test minWithdrawAmount
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'needMemo'
     */
    @Test
    public void needMemoTest() {
        // TODO: test needMemo
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

}
