/*
 * Wallet API Documentation
 * This is a custody wallet service api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openweb3.wallet.models.Currency;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CursorPageCurrency
 */
public class CursorPageCurrencyTest {
    private final CursorPageCurrency model = new CursorPageCurrency();

    /**
     * Model tests for CursorPageCurrency
     */
    @Test
    public void testCursorPageCurrency() {
        // TODO: test CursorPageCurrency
    }

    /**
     * Test the property 'hasNext'
     */
    @Test
    public void hasNextTest() {
        // TODO: test hasNext
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    public void nextCursorTest() {
        // TODO: test nextCursor
    }

    /**
     * Test the property 'prevCursor'
     */
    @Test
    public void prevCursorTest() {
        // TODO: test prevCursor
    }

}
