/*
 * Wallet API Documentation
 * This is a custody wallet service api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openweb3.wallet.models.Balance;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListBalanceHistoryResponse
 */
public class ListBalanceHistoryResponseTest {
    private final ListBalanceHistoryResponse model = new ListBalanceHistoryResponse();

    /**
     * Model tests for ListBalanceHistoryResponse
     */
    @Test
    public void testListBalanceHistoryResponse() {
        // TODO: test ListBalanceHistoryResponse
    }

    /**
     * Test the property 'balances'
     */
    @Test
    public void balancesTest() {
        // TODO: test balances
    }

    /**
     * Test the property 'beginAt'
     */
    @Test
    public void beginAtTest() {
        // TODO: test beginAt
    }

    /**
     * Test the property 'endAt'
     */
    @Test
    public void endAtTest() {
        // TODO: test endAt
    }

}
