/*
 * Wallet API Documentation
 * This is a custody wallet service api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.internal.api;

import io.openweb3.wallet.internal.ApiException;
import io.openweb3.wallet.models.Error;
import io.openweb3.wallet.models.PageAccount;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    /**
     * List accounts
     *
     * List accounts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountsListTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        PageAccount response = api.v1AccountsList(page, size);
        // TODO: test validations
    }

}
