/*
 * Wallet API Documentation
 * This is a custody wallet service api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.internal.api;

import io.openweb3.wallet.internal.ApiException;
import io.openweb3.wallet.models.AuthResult;
import io.openweb3.wallet.models.Credentials;
import io.openweb3.wallet.models.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Disabled
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * User auth
     *
     * User auth
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1UsersAuthTest() throws ApiException {
        Credentials request = null;
        AuthResult response = api.v1UsersAuth(request);
        // TODO: test validations
    }

}
