/*
 * Wallet API Documentation
 * This is a custody wallet service api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.internal.api;

import io.openweb3.wallet.internal.ApiException;
import io.openweb3.wallet.models.Balance;
import io.openweb3.wallet.models.Error;
import io.openweb3.wallet.models.ListBalanceHistoryResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WalletsApi
 */
@Disabled
public class WalletsApiTest {

    private final WalletsApi api = new WalletsApi();

    /**
     * Get wallet balance history
     *
     * Get wallet balance history
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1WalletsGetBalanceTest() throws ApiException {
        Balance response = api.v1WalletsGetBalance();
        // TODO: test validations
    }

    /**
     * List wallet balance history
     *
     * List wallet balance history
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1WalletsListBalanceHistoryTest() throws ApiException {
        String beginAt = null;
        String endAt = null;
        ListBalanceHistoryResponse response = api.v1WalletsListBalanceHistory(beginAt, endAt);
        // TODO: test validations
    }

}
